services:
  mint_admin:
    container_name: mint_admin
    image: code.nexusocean.org/vincent/mint-admin:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mint_api
    networks:
      - mint_net

  mint_api:
    container_name: mint_api
    image: code.nexusocean.org/vincent/mint-api:latest
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      - mint_mongo
    networks:
      - mint_net

  mint_mongo:
    container_name: mint_mongo
    image: mongo:8
    restart: unless-stopped
    expose:
      - 27017
    env_file:
      - .env
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mint_net

networks:
  mint_net:
    driver: bridge
    name: mint_net
