services:
  mint_admin:
    container_name: mint_admin
    image: code.nexusocean.org/vincent/mint-admin:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      NODE_ENV: production
      JWT_SECRET: 2d3ab1f118d64005245b71a0c65ad1a97df8f2785178e741ba826fe4f3dac9c0
      MINT_API_URL: http://mint_api:8080/v1
      MINT_ADMIN_KEY: a294da8a539b886d7df2f4bb47513d6e
      MINT_API_KEY: 5ba0339fe7edb3ffb9f37e608587d626
    depends_on:
      - mint_api
    networks:
      - mint_net

  mint_api:
    container_name: mint_api
    image: code.nexusocean.org/vincent/mint-api:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mint_mongo
    networks:
      - mint_net

  mint_mongo:
    container_name: mint_mongo
    image: mongo:8
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - mint_net

volumes:
  mongo_data:

networks:
  mint_net:
    name: mint_net
    external: true
